// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedthenewmodelstothedatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedthenewmodelstothedatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202502122122329_added-the-new-models-to-the-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
