// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class converteddecimalpricetofloatorderItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(converteddecimalpricetofloatorderItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202502122325263_converted-decimal-price-to-float-orderItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
