// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedcustomerfinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedcustomerfinal));
        
        string IMigrationMetadata.Id
        {
            get { return "202502122251474_updated-customer-final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
